kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: etcd-opera
subjects:
- kind: ServiceAccount
  name: etcd-opera
roleRef:
  kind: Role
  name: etcd-opera
  apiGroup: rbac.authorization.k8s.io
